MODEL:
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  NO_MARGIN: False
  DEVICE_ID: ('0')
  STRIDE_SIZE: [16, 16]
  DIRECT: 0


  

INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST:  [128, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('MSVR310')
  ROOT_DIR: ('/root/shared-nvme/data/')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 8
SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.000035
  IMS_PER_BATCH: 64
  WARMUP_ITERS: 5
  MARGIN: 0.5
  MAX_EPOCHS: 40
  SEED: 42
  
  
  
  

TEST:
  RE_RANKING: 'no'
  WEIGHT: '/root/shared-nvme/ProxyTTT/logs_pro/msvr310/Heat/ViT-B-16train_best.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: "nothing"
  IMS_PER_BATCH: 256


OUTPUT_DIR: './log/msvr310/MHCF'
